# Generated by Django 4.2.2 on 2024-07-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_edit_publication", "Может отменять публикацию продукта"),
                    ("can_edit_description", "Может редактировать описание продукта"),
                    ("can_edit_category", "Может менять категорию любого продукта"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
